version: "3"
services:
  app:
    build:
      context: .
    volumes:
      - .:/app:cached
      - extensions:/home/vscode/.vscode-server/extensions
    # working_dir: /app
    network_mode: host
    tty: true
volumes:
  extensions:

